### PR TITLE
Switched onewire part to Arduino OneWire lib and made code multi sensor aware

### PR DESCRIPTION
**Pull request by altelch**
Hi,

I changed the one wire part to the Arduino included OneWire library. Now it's possible to support the DS18x20 sensor family and even have multipe sensors on the bus. I also changed the mqtt part to provide the sensor id after the temperature (tele/sonoff/TEMPERATURE/1081918D02080021/ 22.9375).
If interested please include this into your code.

Greetings,

           Altelch.

### CODE REVIEW

**Comment by arendst** [comment]
Thx, as I want to keep my implementation as it doesn't need a library I also implemented yours as an alternative. I will release in version 2.0.16

Question: why on earth do you want a resolution of 0.xxx for temperature? I thought 0,x would be enough considering the not so precise sensor (DS18B20). I suppose that if you connect 4 of them at the same location you'll get four different readings.

**Comment by altelch** [comment]
Great! I took the resolution as the multiplier ist 0.0625 so i could see slightest changes.  By sheet precision is +/-0.5 °C. Also have some test setups with tsys01 24 bit high precision sensors on I2C:

tsys01   :  21.668148
ds18s20:  21.8750
ds18s20:  22.0625

So yes, it's below 0.5 sometimes even better. So you might reduce the output to two digits what should be more than enough while still keeping smooth graphs. I plan to implement some more sensors if I can use the I2C bus on the sonoff modules. Temperature/Humidity and absolute or differential pressure are sensor types I have available and some use for. So if you are interested I'll do another pull request when implemented.

Greetings,

               Heiko.

**Comment by altelch** [comment]
Hi, just for fun a 3 Sensor setup with 5 second steps. Readings differ in one bit. So yes, rounding to one digit should be enough but two digits won't hurt.
tele/sonoff/TEMPERATURE/1081918D02080021/ 22.7500
tele/sonoff/TEMPERATURE/1099C08D02080083/ 22.7500
tele/sonoff/TEMPERATURE/103FAF8D02080013/ 22.8125
.
.
.
tele/sonoff/TEMPERATURE/1081918D02080021/ 22.7500
tele/sonoff/TEMPERATURE/1099C08D02080083/ 22.8125
tele/sonoff/TEMPERATURE/103FAF8D02080013/ 22.8125

Greetings,

             Heiko.

**Comment by arendst** [comment]
Heiko thnx. I already decided to make a define in user_config.h where you can decide from 0 - 3 how many decimal digits you want ;-)

I also make the MQTT messages different from yours:
```
11:45:55 MQTT: tele/wemos5/LIGHT = ON
11:45:55 MQTT: tele/wemos5/UPTIME = 0
11:45:55 MQTT: tele/wemos5/RSSI = 82
11:45:55 MQTT: tele/wemos5/DS18x20/1/ADDRESS = 284CC48E04000079
11:45:55 MQTT: tele/wemos5/DS18x20/1/TEMPERATURE = 21.7
11:45:55 MQTT: tele/wemos5/DS18x20/2/ADDRESS = 28FFA67F70160543
11:45:55 MQTT: tele/wemos5/DS18x20/2/TEMPERATURE = 20.8
11:45:55 MQTT: tele/wemos5/DHT/TEMPERATURE = 21.8
11:45:55 MQTT: tele/wemos5/DHT/HUMIDITY = 74.4
11:45:55 MQTT: tele/wemos5/TIME = 2016-11-18T11:45:55
```
The index will also show in the webpage; no need for the full address:
```
DSB1 Temperature:	21.7°C
DSB2 Temperature:	20.8°C

DHT Temperature:	21.8°C
DHT Humidity:    	83.7%
```
To be released this afternoon...

**Comment by altelch** [comment]
Hi Theo,

On 18.11.2016 11:48, Theo Arends wrote:
>
> Heiko thnx. I already decided to make a define in user_config.h where 
> you can decide from 0 - 3 how many decimal digits you want ;-)
>

*hehe* Flexibility is fine.

> I also make the MQTT messages different from yours:
>
> |11:45:55 MQTT: tele/wemos5/LIGHT = ON 11:45:55 MQTT: 
> tele/wemos5/UPTIME = 0 11:45:55 MQTT: tele/wemos5/RSSI = 82 11:45:55 
> MQTT: tele/wemos5/DS18x20/1/ADDRESS = 284CC48E04000079 11:45:55 MQTT: 
> tele/wemos5/DS18x20/1/TEMPERATURE = 21.7 11:45:55 MQTT: 
> tele/wemos5/DS18x20/2/ADDRESS = 28FFA67F70160543 11:45:55 MQTT: 
> tele/wemos5/DS18x20/2/TEMPERATURE = 20.8 11:45:55 MQTT: 
> tele/wemos5/DHT/TEMPERATURE = 21.8 11:45:55 MQTT: 
> tele/wemos5/DHT/HUMIDITY = 74.4 11:45:55 MQTT: tele/wemos5/TIME = 
> 2016-11-18T11:45:55 |
>
> The index will also show in the webpage; no need for the full address:
>
> |DSB1 Temperature: 21.7°C DSB2 Temperature: 20.8°C DHT Temperature: 
> 21.8°C DHT Humidity: 83.7% |
>
> To be released this afternoon...
>

Ok, I think I can live with this. Has one sideeffect. If you add or 
replace a sensor the ordering will change. One sensor setup normally is 
persistent but after
changes and rescanning the bus the ordering can change so you can't rely 
on your sensor count number. Thats why I decided to use the address as 
separator. Same for web display when adding a DSB3 it may become DSB1 so 
you always need to take the address into account.

Greetings and Thanks,

     Heiko.

**Comment by arendst** [comment]
Heiko, anticipated this so I'm working on sorting the scanned devices.

**Comment by arendst** [comment]
Released as version 2.0.16 just now

**Comment by altelch** [comment]
Thanks for including :-)

**Pull request closed without merging**
