### PR TITLE
Fix platformio dependencies

### PR DESCRIPTION
**Pull request by thomasf**
I could not build unless I added these

### CODE REVIEW

**Comment by thomasf** [comment]
ESP8266WebServer and DNSServer are required dependencies if the web server is enabled in the user config. This should be a safe merge...

**Comment by porkyneal** [comment]
You could also add a build flag to increase the pubsubclient buffer size. Therefore, no need to modify the source.

e.g. "build_flags = -DMQTT_MAX_PACKET_SIZE=1200"

**Comment by thomasf** [comment]
@porkyneal  Good idea! I have updated the pull request to include that as well.

**Comment by thomasf** [comment]
@arendst  please merge this so that platformio builds works OOTB

**Comment by arendst** [comment]
First: I want as less parameters changed in as less as possible files.

Second: I've been fooling around with the -D directive before but it failed together with -W and -T directives in my previous attempts so that's why I did not add it UNTIL NOW...

Today I tried platformio again.
- It first updates to version 3.2.1.
- Then I copied the latest sonoff folder (3.0.8)  and platfiormio.ini file to a new folder within the platformio realm.
- Without the requested library adds it compiled flawlessly.
- Uploading via webinterface works fine too and after restart it complained (as expected) about the MQTT_MAX_PACKET_SIZE to small.
- I did add the -D directive again (without the requested ESP8266WebServer and DNSServer libraries) and it compiled flawlessly again.
- Uploading the file now does not complain about the MQTT_MAX_PACKET_SIZE so it seems to work fine.

Bottomline: I see no use for adding the ESP8266WebServer and DNSServer libraries. I do not understand why they are needed for someone as there are many other libraries needed that seem to load just fine for them. Again, I did not see a problem in missing libraries; they just loaded fine.

So I did add the -D directive today to github.

Hope to be good friends still...

**Comment by thomasf** [comment]
It seems like the need to add the ESP8266WebServer and DNSServer dependencies might have been a temporary bug, maybe in 3.2.0 or something.. After upgrading to latest platformio it works without it.

**Pull request closed without merging**
