### PR TITLE
platformio changes

### PR DESCRIPTION
**Pull request by wiktorschmidt**
Hey @arendst,

Is there any interest in merging some minor changes that would allow the project to be build in PlatformIO?

This is based on
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/issues/32

LMK

### CODE REVIEW

**Comment by arendst** [comment]
Wiktor, I will merge them myself. Thanks your input.

**Comment by wiktorschmidt** [comment]
thanks. I'm also exploring if there is a way to use the "native" Arduino OTA as described here:
http://docs.platformio.org/en/stable/platforms/espressif8266.html#over-the-air-ota-update
and here:
https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.md#arduino-ide

am I right to assume your approach is different and not immediately compatible with PlatformIO?

**Comment by arendst** [comment]
Yes, my approach is different as I want to initiate the OTA upload from Sonoff using MQTT. This way I can update many Sonoffs at the same time using the GroupTopic.

**Comment by arendst** [comment]
Implemented in 2.0.13 just released.

**Pull request closed without merging**
