### PR TITLE
Add MQTT service discovery with mDNS

### PR DESCRIPTION
**Pull request by guglielmino**
I added a service discovery feature in mqtt_reconnect, with this feature it tries to query for a MQTT service over the network when it can't find default MQTT server. It uses mDNS to lookup up for the service.
Like other features in the firmware I introduced a preprocessor flag to enable/disable it.

### CODE REVIEW

**Comment by arendst** [comment]
I'll look into it.

**Comment by whhsn** [comment]
This maybe better added to the config screen

**Comment by guglielmino** [comment]
What is better to add in config screen? The setting for enabling the MQTT discovery using mDNS?

**Comment by ekgerke** [comment]
Hi.

Would make a lot of sense to advertize each switch on local network via mDNS when the library is already used somewhere. I was just looking into adding that functionality to my private testing branch. I really miss the ability to connect to http://kitchen.local/

Gerke.

**Comment by arendst** [comment]
Ekgerke, if you so keen on using the http interface why don't you install a local dns server? No need for your equipment to install local solutions and it works with all your in house equipment.

I use dnsmasq with great succes.

**Comment by ekgerke** [comment]
not really using the http interface for anything more than logging really. a weird thing with my network settings is that at some moments the sonoffs fail to resolve the mqtt host by name (macmini.local in my case) haven't really dug into it too much to figure what's going on. My whole point was that I really like zeroconf stuff in my network.

**Comment by arendst** [comment]
Implemented in version 3.1.10 just released. Made some changes I think are usefull but I can't test it as mDNS fails to find my MQTT server (probably due to my DNS server).

Can you give it a try and let me know if this satisfies your mDNS need.

**Comment by guglielmino** [comment]
When You call mdns_discoverMQTTServer() return value isn't checked in Your source. So, if the first time it fails, subsequent attempts to connect to MQTT server are useless.
Why don't You just take my code? It's made in a separate file also to maintain code clean.

**Comment by guglielmino** [comment]
A quick info: if You want to test the mDNS query on Mac You can just use this command:

`dns-sd -R "mac_host_name"  _mqtt._tcp. local 1883`

Issuing this command You advertise a MQTT service listening on port 1883 on Your machine, I use  mosquitto running on my machine to make end2end tests.
On Linux You can use avahi daemon to do the same thing.

**Comment by timtimsson** [comment]
Hello guglielmino, 
i don't know mDNS - do you have a link to a decent wiki? 
How can i use this with my Raspberry? 
Thanks

**Comment by guglielmino** [comment]
Hello Tim,
I think You can start from [here](https://en.wikipedia.org/wiki/Multicast_DNS)

You can test it on a Raspberry installing a MQTT broker (mosquitto for example) and avahi-daemon for advertising it. Advertising MQTT on the network with avahi is quite simple, the only thing You need is to put a file named `mqtt.service` in `/etc/avahi/services/` (some time is in a different place, You have to check Your avahi installation).
Content of the file describes how to advertise the service, in case of MQTT:

```
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">MQTT on %h</name>
  <service>
   <type>_mqtt._tcp</type>
   <port>1883</port>
  </service>
</service-group>
```

With this configuration Sonoff with service discovery will be able to discover the MQTT server without any configuration (they obviously have to be on the same network).

Let me know
Fabrizio

**Comment by timtimsson** [comment]
very interesting, but many question :)
i found the folder/services on my pi and i created a mqtt.service file.
my mqtt is password protect.
And now? how can i see, that the device found  my raspi.local?

**Comment by guglielmino** [comment]
Now turn on the Sonoff and listen on the serial to check if it discover the mqtt server and try to connect.

**Comment by timtimsson** [comment]
... i can't listen on serial - i use the webIF
20:42:00 MQTT: Attempting connection...
20:42:01 mDNS: Query done with 1 mqtt services found
20:42:01 mDNS: Service found on raspi ip 10.1.x.x port 1883
thats all ?
If i use >avahi-browse -art , i can see all my sonoff devices like this:
=   eth0 IPv4 ESP_S03-1279                                  Web-Angebot          local
   hostname = [esp_s03-1279.local]
   address = [10.1.X.x]
   port = [80]
   txt = []

**Comment by guglielmino** [comment]
Looking at Your log the device found the MQTT server, so the mDNS part works.
It's not clear if the connection with MQTT server was also good (if You have user/password these have to be defined in Sonoff configuration by hand).

**Comment by timtimsson** [comment]
Thank you for your explanations

**Pull request closed without merging**
