### PR TITLE
HUE API brightness extension and power save referencing #272

### PR DESCRIPTION
**Pull request by altelch**
HUE API supports setting the brightness. Echo device can controll brightness of LED strip.
Added wifi_set_sleep_type(LIGHT_SLEEP_T) when goint into STA mode, sleeping for 50ms in loop to see if any power saving occures. Animations still seem to run, no problems doing web calls or MQTT during my tests.

Greetings,

               Heiko.

### CODE REVIEW

**Comment by altelch** [comment]
Checked power consumption while measuring the current on the 5V line. Without the modifications I get a current of about 73mA constantly. With power saving enabled I can see drops down to 18mA so there seems to be a real saving just from sleeping 50ms every loop.

**Comment by marcelveldt** [comment]
I can confirm the power savings. Measured the current on the 230V input of the sonoff unit. Without the modification it's about 0,6 watts continuously and with the light_sleep and delay code added, it drops down to 0,2-0,3 watts which is a big save if you have many sonoffs in your house always powered on.

**Comment by arendst** [comment]
Implemented in version 3.2.12 just released

**Comment by altelch** [comment]
Just for information. I'm running scheme=3 with sleep enabled. Sleep values which add up to 100 tend to cause artefacts during displaying animation. sleep = 0 runs without flaws, 49 causes much fewer errors than 50 and 33 seems to run without problems. Testing it quiet a while without any problems. Divisors of 100 or 1000 should be omitted, values below 50 tend to work in LED mode.

Greetings,

             Heiko.

**Comment by altelch** [comment]
More tests regarding powersave show a dependency with the number of LEDs used. With 90 LEDs connected I need sleep 0 to run the animations without error. I'm currently using DMA mode.

**Comment by altelch** [comment]
Ok, a Pixel color needs 24*50uS to change the settings what is 1.2ms x 90 LEDs is 108ms and longer than the state machine steps of 100ms. That explains why there is no time for delay in longer strips.

**Pull request closed without merging**
