### PR TITLE
Push Button support for Wall Switch

### PR DESCRIPTION
**Pull request by 0n3-70uch**
Hello,

I added a support for a push button. 
Activate with PUSHBUTTON or PUSHBUTTON_INV in user_config.h.

Tested with standard Sonoff.

Greetings
Fabi

### CODE REVIEW

**Comment by arendst** [comment]
Thnx. Will implement next release

**Comment by 0n3-70uch** [comment]
Oh very cool... Thanks.

I found a little "problem". The program send a MQTT message when you press the push button and a second MQTT message when you release the push button. Its not so fine... Hope you have an easy solution for this problem.

**Comment by arendst** [comment]
Yes I will implement debounce.

**Comment by arendst** [comment]
Implemented in version 3.0.2 just released

**Comment by 0n3-70uch** [comment]
...and tested. Nice debounce solution and thank you for implementing. 

I found a little issue:
When I push the button I got no status update in my domoticz webgui. I must activate "DOMOTICZ_UPDATE_TIMER" in user_config.h to see the status update. 

Greetings Fabi

**Comment by arendst** [comment]
Fixed Domoticz (and extra status message) misbehaving in version 3.0.3 just released.

**Comment by 0n3-70uch** [comment]
Thank you.

**Pull request closed without merging**
