### PR TITLE
WS2812 LED Support

### PR DESCRIPTION
**Pull request by altelch**
Hi,

recreated the rudimentary WS2812 LED support. Minimum config is a LED Strip connected to 3.3V, GND and the RX-Pin of the Sonoff. Also put an 1000uF Capacitor between GND and 3.3V. For more Power I soldert a Pin into an "empty" Socket going to the empty BusyBee uC and connected that one to the + pin of the capacitor close to the relay (see schematics). There we can get 5V directly behind the EE10 transformer. Due to spec sheet this one sould provide up to 5W. Don't know how much 3.3V rail can provide but running 30LEDs at 0xFFFFFF and switching on the relay didn't crash the sonoff but it gets really hot after a while. So I'd not use this mode with more than a few leds connected. On the other hand one could connect a 5V power supply to the relais, generate a common ground and connect RX to the strip.

I currently implemented two cmnd modes:

cmdn/sonoff/LED<id> #RRGGBB

and

cmnd/sonoff/STRIP #RRGGBB'

to set all LEDs.

Had to rewrite your index parser code a bit. It's a very rudimentary implementation but If you like the Idee feel free to integrate it. That is a very first trial and I don't know If I'll follow that idea for multi relay devices. I cleaned up my forked repo and removed all the HUE Stuff.

Greetings,

       Heiko.

### CODE REVIEW

**Comment by altelch** [comment]
HUE Stuff now added as new commit. Makes diff easier.

**Comment by don-willingham** [comment]
I'd like to see how the HUE emulation works out. I have WIP branch for the additional tcp port for Wemo https://github.com/don-willingham/Sonoff-MQTT-OTA-Arduino/tree/dual-wemo

**Comment by altelch** [comment]
The HUE code is somehow related to the LED stuff. With the WeMo emulation I can't set RGB values and intensity as the wemo devices don't support this. So if it's possible to get a minimal hue emulation working I could solve the multi channel device problem AND RGB/Intensity stuff with one emulation type. I thint the wemo code is still good for the simple sonoff device and switching one device as I'd guess it will be smaller than what is necessary to get HUE working.

**Comment by don-willingham** [comment]
It is probably best to provide the most choice. Users will likely choose on our the other. I'd like to experiment with LED light strips. I know some strips LEDs can be individually addressed. For color, the hue emulation would be required. I wonder how similar the WeMo dimmer light switches and sockets switch APIs are, just in case you wanted just a dinner. As far as switches go there is also a TP Link plug with its own interface.

**Comment by altelch** [comment]
Remerged 3.2.3 into my code. Detection process of HUE emulation now works. Need to implement api part for switching on/off a single device and enumerate the real devices the sonoff provides. Then we have the same functionality for multichannel devices as we now have with the wemo emulation. Additional work is required to get the LED strip working as HUE Lamp.

**Comment by altelch** [comment]
Basic HUE support now working. Multi channel Sonoffs enumerate their channels as FriendlyName[1..N] and echo finds them. Switching on/off works. Didn't implement multiple friendlyName variables as I think Theo knows better how he wants this done especially when handling/changing SPIFFS.

**Comment by arendst** [comment]
Heiko, merged your code with mine to get you going regarding future hue changes.
I will expand the ws2812 code and prepare the experimental version in the next days to have one version going forward.

**Comment by don-willingham** [comment]
My branch https://github.com/don-willingham/Sonoff-MQTT-OTA-Arduino/tree/dual-wemo created an array of friendly names, so I could spell them out as "Living Room Fan" and "Living Room Light". Otherwise, I would have to create a series of groups in the Alexa app to map the names I want to some-name1, some-name2.

**Comment by altelch** [comment]
Hi Theo,

regarding your note about external 5V supply. My strip works with also with 3.3V. So a small strip can be driven with a basic sonoff via the 5pin header. It would be better to use external power if you have more than about 5 LEDs I'd guess. The schematics dont't give me enough info to see how much current is available on 3.3V.

Greetings,

           Heiko.

**Comment by altelch** [comment]
Ok, remerged with my code. Changed to DMA mode, seems to work :-) Thank you for integrating. Will test the HUE Part tomorrow and then go on.

**Pull request closed without merging**
